AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: AIDE - Program Service

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        DATABASE_URL: !Ref DatabaseUrl
        EVENT_BUS_NAME:
          Fn::ImportValue:
            Fn::Sub: aide-identity-${Environment}
        COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
        COGNITO_CLIENT_ID: !Ref CognitoClientId

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod

  DatabaseUrl:
    Type: String

  CognitoUserPoolId:
    Type: String

  CognitoClientId:
    Type: String

Resources:
  ProgramApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment

      Auth:
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer:
                Fn::Sub:
                  - https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPoolId}
                  - UserPoolId: !Ref CognitoUserPoolId
              audience:
                - !Ref CognitoClientId

            IdentitySource: "$request.header.Authorization"

        DefaultAuthorizer: CognitoAuthorizer
  
  CreateProgram:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image

      ImageConfig:
        Command:
          - dist/handlers/createProgram.handler

      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName:
              Fn::ImportValue:
                Fn::Sub: aide-identity-${Environment}

      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ProgramApi
            Path: /programs
            Method: POST

    Metadata:
      DockerTag: program-service
      DockerContext: ../../services/programs
      Dockerfile: Dockerfile

  GetAllPrograms:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command:
          - dist/handlers/getAllPrograms.handler

      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName:
              Fn::ImportValue:
                Fn::Sub: aide-identity-${Environment}
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ProgramApi
            Path: /programs
            Method: GET

    Metadata:
      DockerTag: program-service
      DockerContext: ../../services/programs
      Dockerfile: Dockerfile

  GetProgram:
    Type: AWS::Serverless::Function

    Properties:
      PackageType: Image
      ImageConfig:
        Command:
          - dist/handlers/getProgram.handler

      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName:
              Fn::ImportValue:
                Fn::Sub: aide-identity-${Environment}

      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ProgramApi
            Path: /programs/{id}
            Method: GET

    Metadata:
      DockerTag: program-service
      DockerContext: ../../services/programs
      Dockerfile: Dockerfile

  SetProgramStatus:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image

      ImageConfig:
        Command:
          - dist/handlers/setProgramStatus.handler

      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName:
              Fn::ImportValue:
                Fn::Sub: aide-identity-${Environment}

      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ProgramApi
            Path: /programs/status/{id}
            Method: PATCH
    
    Metadata:
      DockerTag: program-service
      DockerContext: ../../services/programs
      Dockerfile: Dockerfile

  SetRequiredCoursesForProgram:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      
      ImageConfig:
        Command:
          - dist/handlers/setRequiredCoursesForProgram.handler
      
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName:
              Fn::ImportValue:
                Fn::Sub: aide-identity-${Environment}

      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ProgramApi
            Path: /programs/courses/{id}
            Method: PATCH

    Metadata:
      DockerTag: program-service
      DockerContext: ../../services/programs
      Dockerfile: Dockerfile
  
  UpdateProgram:
    Type: AWS::Serverless::Function
  
    Properties:
      PackageType: Image

      ImageConfig:
        Command:
          - dist/handlers/updateProgram.handler

      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName:
              Fn::ImportValue:
                Fn::Sub: aide-identity-${Environment}
              
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ProgramApi
            Path: /programs/update/{id}
            Method: PATCH

    Metadata:
      DockerTag: program-service
      DockerContext: ../../services/programs
      Dockerfile: Dockerfile

  CourseCreatedListener:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image

      ImageConfig:
        Command:
          - dist/events/onCourseCreated/courseCreated.handler

      Events:
        CourseCreatedEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName:
              Fn::ImportValue:
                Fn::Sub: aide-identity-${Environment}

            Pattern:
              source:
                - aide.course

              detail-type:
                - course.created
    Metadata:
      DockerTag: program-service
      DockerContext: ../../services/programs
      Dockerfile: Dockerfile

  CourseUpdatedListener:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image

      ImageConfig:
        Command:
          - dist/events/onCourseUpdated/courseUpdated.handler

      Events:
        CourseUpdatedEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName:
              Fn::ImportValue:
                Fn::Sub: aide-identity-${Environment}

            Pattern:
              source:
                - aide.course

              detail-type:
                - course.updated
                
    Metadata:
      DockerTag: program-service
      DockerContext: ../../services/programs
      Dockerfile: Dockerfile